apiVersion: v1
kind: Service
metadata:
  name: simplescaler-exporter-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'
  labels:
    app: simplescaler-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: simplescaler-exporter