apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: simplescaler-exporter
  name: simplescaler-exporter-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: simplescaler-exporter
  name: simplescaler-exporter-cr
rules:
- apiGroups:
  - arjunnaik.in
  resources:
  - scalers
  verbs:
  - get 
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: simplescaler-exporter
  name: simplescaler-exporter-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simplescaler-exporter-cr
subjects:
- kind: ServiceAccount
  name: simplescaler-exporter-sa